modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
#issueTrackerURL = "https://github.com/TonPseudo/Cobblemon-Marks/issues"

[[mods]]
modId = "cobblemonmarks"
version = "${version}"
displayName = "Cobblemon Marks"
authors = "Darcosse"
description = '''
A Cobblemon addon that adds a mark farming system.
Complete configurable objectives like defeating specific types, fishing,
or battling in specific weather conditions to unlock Marks for your Pokémon.
Includes real-time progress tracking in the summary screen!
'''
#logoFile = "icon.png"

[[dependencies.cobblemonmarks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemonmarks]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemonmarks]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "cobblemonmarks.mixins.json"